image: Visual Studio 2019

environment:
  matrix:
    - MSYSTEM: MINGW64
#    - MSYSTEM: MINGW32

# https://www.postgresql.org/message-id/flat/f1caef93-9640-022e-9211-bbe8755a56b0%402ndQuadrant.com
matrix:
  allow_failures:
    - MSYSTEM: MINGW64

install:
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "pacman --noconfirm -S --needed ${MINGW_PACKAGE_PREFIX}-gettext ${MINGW_PACKAGE_PREFIX}-icu ${MINGW_PACKAGE_PREFIX}-libxslt ${MINGW_PACKAGE_PREFIX}-openssl"
  - sh -l -c "curl -L http://cpanmin.us | perl - --self-upgrade"
  - sh -l -c "cpanm --notest IPC::Run"


build_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - mkdir C:\projects\postgres\dist
  - sh -l -c "./configure --host=x86_64-w64-mingw32 --prefix=C:/projects/postgres/dist  --enable-debug --enable-tap-tests --enable-nls  --with-icu --with-ldap --with-libxml --with-libxslt --with-openssl"
  - pwd
#  - sh -l -c "echo "teste" > arquivo.txt"  
#  - sh -l -c "make clean"
  - sh -l -c "make -j2"
  - sh -l -c "make install -j2"
  - set PATH=C:/projects/postgres/dist/bin;C:/projects/postgres/dist/include/server;%PATH%
  - cd C:\projects\postgres\contrib\pglogical
#  - sh -l -c "make distclean"
  - sh -l -c "make"
  - sh -l -c "make install"
  - 7z a -r postgre.zip C:\projects\postgres\dist
  - appveyor PushArtifact postgre.zip
  
artifacts:
  - path: postgre.zip
    name: postgres


on_failure:
  - set HOME=.
  - sh -l -c "test -f config.status || cat config.log"
  - sh -l -c "find . -name regression.diffs | xargs cat"
